
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `carto-images` (
                                `idPartenariat` int(11) NOT NULL,
                                `idPhoto` int(11) NOT NULL,
                                `ImageUrl` varchar(512) NOT NULL,
                                `verified` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



INSERT INTO `carto-images` (`idPartenariat`, `idPhoto`, `ImageUrl`, `verified`) VALUES
(27, 13, 'distritos.webp', 0),
(11, 18, 'NX-43325.jpg', 1),
(11, 20, '11248589.webp', 1);



CREATE TABLE `carto-partenariats` (
                                      `idPartenariat` int(11) NOT NULL,
                                      `id` varchar(2) NOT NULL,
                                      `Ville` varchar(128) NOT NULL,
                                      `NomStructure` varchar(128) NOT NULL,
                                      `Departement` varchar(128) NOT NULL,
                                      `NbEtudiants` int(128) NOT NULL,
                                      `Messages` longtext NOT NULL,
                                      `latitude` double NOT NULL,
                                      `longitude` double NOT NULL,
                                      `verified` tinyint(1) DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



INSERT INTO `carto-partenariats` (`idPartenariat`, `id`, `Ville`, `NomStructure`, `Departement`, `NbEtudiants`, `Messages`, `latitude`, `longitude`, `verified`) VALUES
(1, 'US', 'Seattle', 'University of Seattle', 'MEPHY', 1, '', 47.6038321, -122.3300624, 1),
(2, 'MX', 'Cancún', 'University of Cancun', 'GEA', 3, '', 21.1617854, -86.8510468, 1),
(3, 'KZ', 'Astana', '', '', 0, '', 0, 0, 0),
(10, 'ES', 'Madrid', 'University of Madrid', 'GB', 2, '', 40.4167047, -3.7035825, 1),
(11, 'FR', 'Aix-en-Provence', 'Faculté de Science', 'TC', 6, 'test\r\nlien : https://www.univ-amu.fr/\r\nadresse mail : test.univ@gmail.com', 43.5298424, 5.4474738, 1),
(14, 'DZ', 'Djanet', 'University of Djanet', 'TC', 1, '', 24.071521, 9.615584725366856, 1),
(16, 'ES', 'Barcelone', 'Université de Barcelone', 'INFO', 12, '', 41.3828939, 2.1774322, 1),
(17, 'NO', 'Trondheim', 'Université des Sciences', 'TC', 0, '', 63.4305658, 10.3951929, 1),
(18, 'RE', 'Saint-Leu', '', '', 0, '', 0, 0, 0),
(23, 'RU', 'Saint-Pétersbourg', 'University of Saint-Pétersbourg', 'GEII', 1, '', 59.9606739, 30.1586551, 1),
(26, 'FR', 'Marseille', 'Faculté de Droit', 'TC', 0, 'Test\r\nTEST\r\ntest\r\nTest', 43.2961743, 5.3699525, 1),
(27, 'GB', 'Londres', 'University of London', 'GEII', 8, '', 51.5073219, -0.1276474, 1),
(30, 'SN', 'Senegal', 'University of Senegal', 'INFO', 2, '', 14.4750607, -14.4529612, 1),
(36, 'IT', 'venise', 'test', 'test', 2, '', 45.4371908, 12.3345898, 1),
(37, 'CA', 'Quebec', 'University of Quebec', 'GEA', 4, '', 52.4760892, -71.8258668, 1);



CREATE TABLE `carto-pays` (
                              `id` varchar(2) NOT NULL,
                              `nom` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `carto-pays` (`id`, `nom`) VALUES
('AD', 'Andorre'),
('AE', 'Émirats arabes unis'),
('AF', 'Afghanistan'),
('AG', 'Antigua-et-Barbuda'),
('AI', 'Anguilla'),
('AL', 'Albanie'),
('AM', 'Arménie'),
('AO', 'Angola'),
('AQ', 'Antarctique'),
('AR', 'Argentine'),
('AS', 'Samoa américaines'),
('AT', 'Autriche'),
('AU', 'Australie'),
('AW', 'Aruba'),
('AX', 'Åland, Îles'),
('AZ', 'Azerbaïdjan'),
('BA', 'Bosnie-Herzégovine'),
('BB', 'Barbade'),
('BD', 'Bangladesh'),
('BE', 'Belgique'),
('BF', 'Burkina Faso'),
('BG', 'Bulgarie'),
('BH', 'Bahreïn'),
('BI', 'Burundi'),
('BJ', 'Bénin'),
('BL', 'Saint-Barthélémy'),
('BM', 'Bermudes'),
('BN', 'Brunéi Darussalam'),
('BO', 'Bolivie, État Plurinational de'),
('BQ', 'Bonaire, Saint-Eustache et Saba'),
('BR', 'Brésil'),
('BS', 'Bahamas'),
('BT', 'Bhoutan'),
('BV', 'Bouvet, Île'),
('BW', 'Botswana'),
('BY', 'Bélarus'),
('BZ', 'Belize'),
('CA', 'Canada'),
('CC', 'Cocos (Keeling), Îles'),
('CD', 'République démocratique du Congo'),
('CF', 'Centrafricaine, République'),
('CG', 'Congo'),
('CH', 'Suisse'),
('CI', 'Côte d’Ivoire'),
('CK', 'Îles Cook'),
('CL', 'Chili'),
('CM', 'Cameroun'),
('CN', 'Chine'),
('CO', 'Colombie'),
('CR', 'Costa Rica'),
('CU', 'Cuba'),
('CV', 'Cap-Vert'),
('CW', 'Curaçao'),
('CX', 'Christmas, Île'),
('CY', 'Chypre'),
('CZ', 'Tchèque, République'),
('DE', 'Allemagne'),
('DJ', 'Djibouti'),
('DK', 'Danemark'),
('DM', 'Dominique'),
('DO', 'Dominicaine, République'),
('DZ', 'Algérie'),
('EC', 'Équateur'),
('EE', 'Estonie'),
('EG', 'Égypte'),
('EH', 'Sahara occidental'),
('ER', 'Érythrée'),
('ES', 'Espagne'),
('ET', 'Éthiopie'),
('FI', 'Finlande'),
('FJ', 'Fidji'),
('FK', 'Falkland, Îles (Malvinas)'),
('FM', 'Micronésie, États Fédérés de'),
('FO', 'Féroé, Îles'),
('FR', 'France'),
('GA', 'Gabon'),
('GB', 'Royaume-Uni'),
('GD', 'Grenade'),
('GE', 'Géorgie'),
('GF', 'Guyane Française'),
('GG', 'Guernesey'),
('GH', 'Ghana'),
('GI', 'Gibraltar'),
('GL', 'Groenland'),
('GM', 'Gambie'),
('GN', 'Guinée'),
('GP', 'Guadeloupe'),
('GQ', 'Guinée équatoriale'),
('GR', 'Grèce'),
('GS', 'Géorgie du Sud et les îles Sandwich du Sud'),
('GT', 'Guatemala'),
('GU', 'Guam'),
('GW', 'Guinée-Bissau'),
('GY', 'Guyana'),
('HK', 'R.A.S. chinoise de Hong Kong'),
('HM', 'Heard et MacDonald, Îles'),
('HN', 'Honduras'),
('HR', 'Croatie'),
('HT', 'Haïti'),
('HU', 'Hongrie'),
('ID', 'Indonésie'),
('IE', 'Irlande'),
('IL', 'Israël'),
('IM', 'Île de Man'),
('IN', 'Inde'),
('IO', 'Océan Indien, Territoire Britannique de L\''),
('IQ', 'Irak'),
('IR', 'Iran, République Islamique d\''),
('IS', 'Islande'),
('IT', 'Italie'),
('JE', 'Jersey'),
('JM', 'Jamaïque'),
('JO', 'Jordanie'),
('JP', 'Japon'),
('KE', 'Kenya'),
('KG', 'Kirghizistan'),
('KH', 'Cambodge'),
('KI', 'Kiribati'),
('KM', 'Comores'),
('KN', 'Saint-Kitts-et-Nevis'),
('KP', 'Corée, République Populaire Démocratique de'),
('KR', 'Corée, République de'),
('KW', 'Koweït'),
('KY', 'Caïmanes, Îles'),
('KZ', 'Kazakhstan'),
('LA', 'Lao, République Démocratique Populaire'),
('LB', 'Liban'),
('LC', 'Sainte-Lucie'),
('LI', 'Liechtenstein'),
('LK', 'Sri Lanka'),
('LR', 'Libéria'),
('LS', 'Lesotho'),
('LT', 'Lituanie'),
('LU', 'Luxembourg'),
('LV', 'Lettonie'),
('LY', 'Libye'),
('MA', 'Maroc'),
('MC', 'Monaco'),
('MD', 'Moldavie'),
('ME', 'Monténégro'),
('MF', 'Saint-Martin (Partie Française)'),
('MG', 'Madagascar'),
('MH', 'Marshall, Îles'),
('MK', 'Macédoine, L\'ex-république Yougoslave de'),
('ML', 'Mali'),
('MM', 'Myanmar'),
('MN', 'Mongolie'),
('MO', 'R.A.S. chinoise de Macao'),
('MP', 'Mariannes du Nord, Îles'),
('MQ', 'Martinique'),
('MR', 'Mauritanie'),
('MS', 'Montserrat'),
('MT', 'Malte'),
('MU', 'Maurice'),
('MV', 'Maldives'),
('MW', 'Malawi'),
('MX', 'Mexique'),
('MY', 'Malaisie'),
('MZ', 'Mozambique'),
('NA', 'Namibie'),
('NC', 'Nouvelle-Calédonie'),
('NE', 'Niger'),
('NF', 'Norfolk, Île'),
('NG', 'Nigéria'),
('NI', 'Nicaragua'),
('NL', 'Pays-Bas'),
('NO', 'Norvège'),
('NP', 'Népal'),
('NR', 'Nauru'),
('NU', 'Niue'),
('NZ', 'Nouvelle-Zélande'),
('OM', 'Oman'),
('PA', 'Panama'),
('PE', 'Pérou'),
('PF', 'Polynésie française'),
('PG', 'Papouasie-Nouvelle-Guinée'),
('PH', 'Philippines'),
('PK', 'Pakistan'),
('PL', 'Pologne'),
('PM', 'Saint-Pierre-et-Miquelon'),
('PN', 'Pitcairn'),
('PR', 'Porto Rico'),
('PS', 'État de Palestine'),
('PT', 'Portugal'),
('PW', 'Palaos'),
('PY', 'Paraguay'),
('QA', 'Qatar'),
('RE', 'Réunion'),
('RO', 'Roumanie'),
('RS', 'Serbie'),
('RU', 'Russie, Fédération de'),
('RW', 'Rwanda'),
('SA', 'Arabie saoudite'),
('SB', 'Salomon, Îles'),
('SC', 'Seychelles'),
('SD', 'Soudan'),
('SE', 'Suède'),
('SG', 'Singapour'),
('SH', 'Sainte-Hélène'),
('SI', 'Slovénie'),
('SJ', 'Svalbard et Île Jan Mayen'),
('SK', 'Slovaquie'),
('SL', 'Sierra Leone'),
('SM', 'Saint-Marin'),
('SN', 'Sénégal'),
('SO', 'Somalie'),
('SR', 'Suriname'),
('SS', 'Soudan du Sud'),
('ST', 'Sao Tomé-et-Principe'),
('SV', 'El Salvador'),
('SX', 'Saint-Martin (Partie Néerlandaise)'),
('SY', 'Syrienne, République Arabe'),
('SZ', 'Swaziland'),
('TC', 'Turks et Caïques, Îles'),
('TD', 'Tchad'),
('TF', 'Terres australes françaises'),
('TG', 'Togo'),
('TH', 'Thaïlande'),
('TJ', 'Tadjikistan'),
('TK', 'Tokelau'),
('TL', 'Timor-Leste'),
('TM', 'Turkménistan'),
('TN', 'Tunisie'),
('TO', 'Tonga'),
('TR', 'Turquie'),
('TT', 'Trinité-et-Tobago'),
('TV', 'Tuvalu'),
('TW', 'Taïwan, Province de Chine'),
('TZ', 'Tanzanie, République Unie de'),
('UA', 'Ukraine'),
('UG', 'Ouganda'),
('UM', 'Îles mineures éloignées des États-Unis'),
('US', 'États-Unis'),
('UY', 'Uruguay'),
('UZ', 'Ouzbékistan'),
('VA', 'État de la Cité du Vatican'),
('VC', 'Saint-Vincent-et-les Grenadines'),
('VE', 'Venezuela, République Bolivarienne du'),
('VG', 'Îles Vierges britanniques'),
('VI', 'Îles Vierges des États-Unis'),
('VN', 'Viêt Nam'),
('VU', 'Vanuatu'),
('WF', 'Wallis-et-Futuna'),
('WS', 'Samoa'),
('YE', 'Yémen'),
('YT', 'Mayotte'),
('ZA', 'Afrique du Sud'),
('ZM', 'Zambie'),
('ZW', 'Zimbabwe');


ALTER TABLE `carto-images`
    ADD PRIMARY KEY (`idPhoto`) USING BTREE,
    ADD KEY `Foreign Key` (`idPartenariat`);


ALTER TABLE `carto-partenariats`
    ADD PRIMARY KEY (`idPartenariat`),
    ADD KEY `id` (`id`);


ALTER TABLE `carto-pays`
    ADD PRIMARY KEY (`id`);


ALTER TABLE `carto-images`
    MODIFY `idPhoto` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;


ALTER TABLE `carto-partenariats`
    MODIFY `idPartenariat` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=38;


ALTER TABLE `carto-images`
    ADD CONSTRAINT `Foreign Key` FOREIGN KEY (`idPartenariat`) REFERENCES `carto-partenariats` (`idPartenariat`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;


